version: '3.4'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    environment:
      INFLUXDB_REPORTING_DISABLED: "true"
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_DB: "telegraf"
    ports:
      - "8086:8086"
      - "8082:8082"
      - "8089:8089"

  kapacitor:
    image: kapacitor:latest
    container_name: kapacitor
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    ports:
      - "9092:9092"
    links:
      - influxdb

  chronograf:
    image: chronograf:latest 
    container_name: chronograf
    ports:
      - "8888:8888"
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
      REPORTING_DISABLED: "true"
    depends_on:
      - influxdb
      - kapacitor

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      HOSTNAME: telegraf


